---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kakfa-jmx-exporter
  labels:
    prometheus: main
spec:
  scheme: HTTP
  scrapeInterval: 30s
  scrapeTimeout: 30s
  honorLabels: true
  metricsPath: /metrics
  staticConfigs:   
    {{- range $kafka := .Values.kafka }}    
    - targets: ["{{ $kafka }}:9214"]
      labels:
        instance: {{ $kafka }}
        env: kafka-jmx-hosts 
    {{- end }}      
