---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  labels:
    vm: main
  name: blackbox-exporter
spec:
  scheme: HTTP
  scrape_interval: 30s
  scrapeTimeout: 30s
  honorLabels: true
  path: /probe
  staticConfigs:   
    - targets:
  {{- range $domains := .Values.domains }}        
      - {{ $domains }}   
  {{- end }}  
      labels:
        module: http_2xx
        monitoring_agent: blackbox-exporter
        country: Switzerland   
    - targets:
  {{- range $servers := .Values.servers }}        
      - {{ $servers.server_name }}   
  {{- end }}          
      labels:
        module: icmp_probe
        monitoring_agent: blackbox-exporter            
  relabelConfigs: 
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [module]
      targetLabel: __param_module
    - sourceLabels: [__param_target]
      targetLabel: instance
    - replacement: dnjjs32e8fpbu
      sourceLabels: [__job_name]
      targetLabel: geohash
    - targetLabel: __address__
      replacement: blackbox-exporter:9115  
