---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  labels:
    vm: main
  name: kakfa-jmx-exporter
spec:
  scheme: HTTP
  scrape_interval: 30s
  scrapeTimeout: 30s
  honorLabels: true
  path: /metrics
  staticConfigs:   
    {{- range $kafka := .Values.kafka }}    
    - targets: ["{{ $kafka }}:9214"]
      labels:
        instance: {{ $kafka }}
        env: kafka-jmx-hosts 
    {{- end }}      
