{{- if eq  .Values.daemonset.enabled true }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "single.name" . }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "single.name" .) ""  }}
    {{- include "single.labels" . | nindent 4 }}  
    {{- if .Values.labels  }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{- end }}        
spec:
  selector:
    matchLabels:
      app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "single.name" .) ""  }}     
      {{- if .Values.selector_labels  }}
      {{- toYaml .Values.selector_labels | nindent 6 }}
      {{- end }}
  updateStrategy:
    type: {{ .Values.daemonset.updateStrategy.type | default "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.daemonset.updateStrategy.maxUnavailable | default "1" }}  
  minReadySeconds: {{ .Values.minReadySeconds | default "5" }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      labels:
        app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "single.name" .) ""  }}
        {{- if .Values.labels  }}
        {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.hostNetwork  }}
      hostNetwork: {{ .Values.hostNetwork }} 
      {{- end }}
      ##### pull secret block      
      {{- if .Values.imagePullSecrets  }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}      
      {{- end }} 
      ##### affinity block
      {{- if .Values.affinity  }}
      affinity:
      {{- toYaml .Values.affinity | nindent 10 }}
      {{- end }}
      {{- if .Values.tolerations  }}
      tolerations:
       {{- toYaml .Values.tolerations | nindent 10 }}
      {{- end }}      
      serviceAccountName: {{ include "single.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}      
      ##### priority class block
      {{- if  .Values.priorityClassName }}
      priorityClassName:  {{ .Values.priorityClassName }}
      {{- end }}          
      {{- if .Values.hostAliases  }}       
      hostAliases:
      {{- range $key, $value := .Values.hostAliases }}
      - ip: {{ $key }}
        hostnames:
        -  {{ $value | quote }}
      {{- end }}     
      {{- end }}           
      containers:     
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.repository }}:{{ .Values.containers.tag }}
          imagePullPolicy: {{ .Values.pullPolicy | default "IfNotPresent" }}
          ###### lifecycle
          {{- if .Values.containers.lifecycle  }}
          lifecycle:
          {{- toYaml ( .Values.containers.lifecycle ) | nindent 12 -}}
          {{- end }}    
          ##### container run command
          {{- if .Values.containers.cmd  }}
          command:
          {{- toYaml ( .Values.containers.cmd  )| nindent 12 }}
          {{- end }}
          {{- if .Values.containers.arg  }}
          args:
          {{- toYaml ( .Values.containers.arg )| nindent 12 }}
          {{- end }}     
          ##### container ports 
          ports:
          {{- range (index .Values.containers.containerPort ) }}
          - containerPort: {{ . }}
          {{- end }}            
          ##### resources                    
          {{- if .Values.containers.resources  }}
          resources:
          {{- toYaml (index .Values.containers.resources ) | nindent 12 }}          
          {{- end }}  
          ##### readinessProbe probe
          {{- if .Values.containers.readinessProbe  }}
          readinessProbe:
          {{- toYaml (index .Values.containers.readinessProbe ) | nindent 12 }}
          {{- end }}
          ##### livenessProbe probe
          {{- if .Values.containers.livenessProbe  }}
          livenessProbe:
          {{- toYaml ( .Values.containers.livenessProbe ) | nindent 12 }}
          {{- end }}              
          ###### securityContext
          {{- if .Values.containers.securityContext  }}          
          securityContext:
          {{- toYaml ( .Values.containers.securityContext )| nindent 12 }}   
          {{- end }} 
          ###### volumeMounts     
          {{- if .Values.containers.volumeMounts  }}                                                  
          volumeMounts:
            {{-  toYaml ( .Values.containers.volumeMounts ) | nindent 12 }} 
          {{- end }}   
          ###### env block   
          {{- if .Values.containers.env  }}                    
          env:
            - name: TERM
              value: "xterm"
          {{- range $key, $value := .Values.containers.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }} 
          {{- end }}    

      ##### volumes
      {{- if .Values.volumes  }}
      volumes:
        {{- toYaml .Values.volumes | nindent 12 }} 
      {{- end }}     

{{- end }}
