apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "single.name" . | replace "-spot" "" }}
  labels:
    app: {{ include "single.name" . }}
    {{- include "single.labels" . | nindent 4 }}
    {{- if .Values.labels  }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{ end }}
  {{- with .Values.serviceAccount.annotations }}  
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}   
