---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: netdata-external
  labels:
    prometheus: main
spec:
  scheme: HTTP
  scrapeInterval: 30s
  scrapeTimeout: 30s
  honorLabels: true
  metricsPath: '/api/v1/allmetrics?format=prometheus' 
  staticConfigs:
  {{- range $servers := .Values.servers }}
    - targets: ["{{ $servers.server_ip | default $servers.server_name }}:19999"]
      labels:
        instance: {{ $servers.server_name }}
        env: non-kubernetes 
  {{- end }}           

