{{- if and (.Values.deployment.enabled) .Values.autoscaling.enabled (not .Values.keda.enabled) -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "general.name" . }}
  labels:
    app: {{ include "general.name" . }}
    {{- if .Values.labels  }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{ end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "general.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas | default 3 }}
  metrics:
  {{ if not .Values.autoscaling.metrics }}
  {{- if not ( empty .Values.autoscaling.targetCPUUtilizationPercentage ) }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if not ( empty .Values.autoscaling.targetMemoryUtilizationPercentage ) }}        
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  {{- end }}
  {{ if .Values.autoscaling.metrics }}
  {{- toYaml .Values.autoscaling.metrics | nindent 2 }}    
  {{- end }}
  {{ if .Values.autoscaling.behavior }}
  behavior:
  {{- toYaml .Values.autoscaling.behavior | nindent 4 }}    
  {{- end }}          
{{- end }}
