{{- if or (eq .Values.service.type "ClusterIP")  (eq .Values.service.type "NodePort") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "general.name" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    app: {{ include "general.name" . }}
    {{- include "general.labels" . | nindent 4 }}
    {{- if .Values.labels  }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.port }}
  - port: {{ . }}
    targetPort: {{ . }}
    protocol: TCP
    name: {{ $.Values.service.portname  | default "tcp" }}-{{ . }}
  {{- end }}     
  selector:
    app: {{ regexReplaceAll "-exp-[a-zA-Z0-9]{1,10}$" (include "general.name" .) "" }}
    {{- if .Values.service.extraSelector  }}
    {{- toYaml .Values.service.extraSelector | nindent 4 }}
    {{- end }}
{{- end }}



