{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "general.name" . }}
  labels:
    {{- include "general.labels" . | nindent 4 }}
    {{- if .Values.labels  }}
    {{- toYaml .Values.labels | nindent 4 }}
    {{ end }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "general.name" . }}
{{- end }}
