name: Helm Chart Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  lint-and-package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0
    - name: Lint Helm Chart
      run: helm lint charts/my-chart
    - name: Package Helm Chart
      run: helm package charts/my-chart --destination ./packages
    - name: Upload Packaged Chart to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: helm-chart
        path: ./packages

  publish-to-ghcr:
    runs-on: ubuntu-latest
    needs: lint-and-package

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.13.0

    - name: Authenticate with GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

    - name: Push Chart to GHCR
      run: helm push oci://ghcr.io/${{ github.repository_owner }}/helm-charts ./packages/my-chart-*.tgz

  publish-to-gh-pages:
    runs-on: ubuntu-latest
    needs: lint-and-package

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Deploy Chart to GitHub Pages
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: charts
        release_url: https://github.com/${{ github.repository_owner }}/$GITHUB_REPOSITORY
