name: Publish Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.0


      # Fetch the existing gh-pages branch
      - name: Fetch gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || echo "gh-pages branch does not exist yet"
      
      - name: Copy existing packages and index.yaml
        run: |
          mkdir -p old-packages
          if git checkout gh-pages; then
            cp -r * ./old-packages/ || echo "No existing packages found"
          fi
          ls -la ./
          ls -la ./old-packages/
          

      # Package new Helm charts
      - name: Package Helm Charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" -d packaged/
            fi
          done

      # Merge old and new packages
      - name: Merge old and new packages
        run: |
          ls -la ./
          cp old-packages/* packaged/ || echo "No old packages to copy"
          rm -rf old-packages

      # Generate updated index.yaml
      - name: Generate Helm Repository Index
        run: |
          helm repo index packaged --url https://${{ github.repository_owner }}.github.io/helm-charts/ --merge gh-pages/index.yaml || echo "No existing index.yaml to merge"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packaged
          publish_branch: gh-pages
